In [6]:
import numpy as np

for i in range(3):
    A = np.random.randint(-10, 11, size=(3, 3))
    print("Matrix:")
    print(A)
    
    det = np.linalg.det(A)
    
    if det != 0:
        A_inv = np.linalg.inv(A)
        print("Inverse:")
        print(A_inv)
    
        print("A * A_inv:")
        print(A @ A_inv)
    else:
        print("This matrix is not invertible.")

Matrix:
[[-1 -4 -5]
 [-2 -6  8]
 [ 9  7 -3]]
Inverse:
[[ 0.08920188  0.11032864  0.14553991]
 [-0.15492958 -0.11267606 -0.04225352]
 [-0.09389671  0.06807512  0.00469484]]
A * A_inv:
[[ 1.00000000e+00 -1.94289029e-16 -1.82145965e-17]
 [-1.11022302e-16  1.00000000e+00 -3.46944695e-17]
 [-4.16333634e-17 -8.32667268e-17  1.00000000e+00]]
Matrix:
[[-9 -3  1]
 [ 4  4 -2]
 [ 9  2  4]]
Inverse:
[[-0.18867925 -0.13207547 -0.01886792]
 [ 0.32075472  0.4245283   0.13207547]
 [ 0.26415094  0.08490566  0.22641509]]
A * A_inv:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -5.55111512e-17]
 [ 2.22044605e-16  0.00000000e+00  1.00000000e+00]]
Matrix:
[[ 5  7 -6]
 [ 8 -9  5]
 [ 9  7 -9]]
Inverse:
[[ 0.20264317  0.09251101 -0.08370044]
 [ 0.5154185   0.03964758 -0.3215859 ]
 [ 0.60352423  0.12334802 -0.44493392]]
A * A_inv:
[[ 1.00000000e+00 -5.55111512e-17  2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00  8.32667268e-17  1.0000

In [23]:
import pandas as pd

# load the dataset
df = pd.read_csv("kc_house_data.csv")

# drop ignored columns
df = df.drop(columns=["id", "date", "zipcode"])

# (a)

stats = []

for col in df.columns:
    stats.append({
        "feature": col,
        "mean": df[col].mean(),
        "min": df[col].min(),
        "max": df[col].max(),
        "variance": df[col].var()
    })

stats_df = pd.DataFrame(stats)

print("(a): Mean, Min, Max, Variance\n", stats_df)

# get features with the lowest and highest mean
lowest_mean = stats_df.loc[stats_df["mean"].idxmin()]
highest_mean = stats_df.loc[stats_df["mean"].idxmax()]

print("\nLowest mean feature:")
print(f"{lowest_mean['feature']} | mean = {lowest_mean['mean']}")

print("\nHighest mean feature:")
print(f"{highest_mean['feature']} | mean = {highest_mean['mean']}")

# get features with lowest and highest variance
lowest_var = stats_df.loc[stats_df["variance"].idxmin()]
highest_var = stats_df.loc[stats_df["variance"].idxmax()]

print("\nLowest variance feature:")
print(f"{lowest_var['feature']} | variance = {lowest_var['variance']}")

print("\nHighest variance feature:")
print(f"{highest_var['feature']} | variance = {highest_var['variance']}")


# (b)

corr_df = (
    df.corr(numeric_only=True)["price"]
    .drop("price")
    .reset_index()
)

corr_df.columns = ["feature", "correlation"]
corr_df = corr_df.sort_values(by="correlation", ascending=False)

print("\n(b): Correlation with price")
print(corr_df)

positive_corr = corr_df[corr_df["correlation"] > 0]

print("\nPositively correlated features:")
print(positive_corr)

top_feature = corr_df.iloc[0]
print("\nHighest positive correlation:")
print(f"{top_feature['feature']} | correlation = {top_feature['correlation']}")


# (c)

negative_corr = corr_df[corr_df["correlation"] < 0]

print("\n(c): Negatively correlated features")
if negative_corr.empty:
    print("No features have a negative correlation with price.")
else:
    print(negative_corr)


(a): Mean, Min, Max, Variance
           feature           mean         min           max      variance
0           price  540088.141767  75000.0000  7.700000e+06  1.347824e+11
1        bedrooms       3.370842      0.0000  3.300000e+01  8.650150e-01
2       bathrooms       2.114757      0.0000  8.000000e+00  5.931513e-01
3     sqft_living    2079.899736    290.0000  1.354000e+04  8.435337e+05
4        sqft_lot   15106.967566    520.0000  1.651359e+06  1.715659e+09
5          floors       1.494309      1.0000  3.500000e+00  2.915880e-01
6      waterfront       0.007542      0.0000  1.000000e+00  7.485226e-03
7            view       0.234303      0.0000  4.000000e+00  5.872426e-01
8       condition       3.409430      1.0000  5.000000e+00  4.234665e-01
9           grade       7.656873      1.0000  1.300000e+01  1.381703e+00
10     sqft_above    1788.390691    290.0000  9.410000e+03  6.857347e+05
11  sqft_basement     291.509045      0.0000  4.820000e+03  1.958727e+05
12       yr_built   